/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cc.view;

import br.com.cc.dao.ChamadoDao;
import br.com.cc.model.Chamado;
import br.com.cc.model.Cliente;
import br.com.cc.tableModel.TabelaModeloChamado;
import br.com.cc.utilitarios.SomenteNumeros;
import br.com.cc.utilitarios.Utilitarios;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author alafaria
 */
public class TelaChamados extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroChamados
     */
    TelaFecharChamado enviar;
    TelaClientes enviarContrato;
    ChamadoDao chamadoDao = new ChamadoDao();
    Utilitarios utilitario = new Utilitarios();

    public TelaChamados() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(getToolkit().createImage(getClass().getResource("/imagens/simpress_logo.png")));
        tabelaChamados.setModel(new TabelaModeloChamado(new ChamadoDao().listarChamadoTabela()));
        btExcluir.setEnabled(false);
        btAlterar.setEnabled(false);
        btFecharChamado.setEnabled(false);
        txtConsultaNumeroChamado.setDocument(new SomenteNumeros());
        txtNumeroChamado.setDocument(new SomenteNumeros());
        txtContrato.setDocument(new SomenteNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtChamados = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroChamado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContrato = new javax.swing.JTextField();
        btBuscarContrato = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProblema = new javax.swing.JTextPane();
        txtObservação = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btFecharChamado = new javax.swing.JButton();
        btCadastrarCliente = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        btDataAtual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaChamados = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtConsultaNumeroChamado = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimparTela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Chamados");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/simpress_logo.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Cadastro de Chamados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(296, 296, 296)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jtChamados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtChamados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Número do Chamado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Contrato Cliente:");

        btBuscarContrato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscarContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        btBuscarContrato.setText("Buscar Contrato");
        btBuscarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarContratoActionPerformed(evt);
            }
        });

        txtNomeCliente.setEditable(false);

        txtEndereco.setEditable(false);

        txtContato.setEditable(false);

        txtEmail.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("E-mail:");

        txtTelefone.setEditable(false);

        jScrollPane1.setViewportView(txtProblema);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Data Abertura:");

        comboStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Aberto", "Em atendimento", " " }));
        comboStatus.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Status Chamado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Observação:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Problema:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Contato:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nome Cliente:");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_chamado.png"))); // NOI18N

        btFecharChamado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btFecharChamado.setForeground(new java.awt.Color(255, 0, 51));
        btFecharChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar_chamado.png"))); // NOI18N
        btFecharChamado.setText("Fechar Chamado");
        btFecharChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharChamadoActionPerformed(evt);
            }
        });

        btCadastrarCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/tela_cliente.png"))); // NOI18N
        btCadastrarCliente.setText("Cadastrar Cliente");
        btCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClienteActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btDataAtual.setText("Pegar data atual");
        btDataAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataAtualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNumeroChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscarContrato))
                    .addComponent(txtNomeCliente)
                    .addComponent(txtEndereco)
                    .addComponent(txtContato)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail))
                    .addComponent(jScrollPane1)
                    .addComponent(txtObservação)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btDataAtual)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btFecharChamado)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCadastrarCliente)
                        .addGap(79, 79, 79))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarContrato)
                    .addComponent(btFecharChamado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObservação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btDataAtual)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCadastrarCliente)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jtChamados.addTab("Cadastro Chamados", jPanel2);

        tabelaChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaChamadosMouseClicked(evt);
            }
        });
        tabelaChamados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaChamadosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaChamados);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar Chamado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jLabel15.setText("Número Chamado:");

        txtConsultaNumeroChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaNumeroChamadoActionPerformed(evt);
            }
        });
        txtConsultaNumeroChamado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConsultaNumeroChamadoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(txtConsultaNumeroChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtConsultaNumeroChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        jtChamados.addTab("Consulta Chamados", jPanel3);

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cadastrar.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/alterar.png"))); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimparTela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimparTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.png"))); // NOI18N
        btLimparTela.setText("Limpar Tela");
        btLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(btLimparTela)
                        .addGap(18, 18, 18)
                        .addComponent(btCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btAlterar)
                    .addComponent(btExcluir)
                    .addComponent(btSair)
                    .addComponent(btLimparTela))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarTabela() {
        tabelaChamados.setModel(new TabelaModeloChamado(new ChamadoDao().listarChamadoTabela()));
    }

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarContratoActionPerformed
        // TODO add your handling code here:
        String contrato = txtContrato.getText();

        try {
            if (txtContrato.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo contrato não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
            } else {
                ChamadoDao chamadoDao = new ChamadoDao();
                List<Cliente> listaClientes = chamadoDao.listarClientesPorContrato(contrato);

                for (Cliente cliente : listaClientes) {
                    txtNomeCliente.setText(cliente.getNomeCliente());
                    txtEndereco.setText(cliente.getEndereco());
                    txtContato.setText(cliente.getContato());
                    txtTelefone.setText(cliente.getTelefone());
                    txtEmail.setText(cliente.getEmail());
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na consulta");
        }

    }//GEN-LAST:event_btBuscarContratoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        String numeroChamado = txtNumeroChamado.getText();
        try {
            if (txtNumeroChamado.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo NÚMERO DO CHAMADO não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
            } else if (txtContrato.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo CONTRATO não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
            } else if (txtProblema.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Campo PROBLEMA não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
            } else if (comboStatus.getSelectedItem().equals("Selecione uma opção")) {
                JOptionPane.showMessageDialog(null, "Em STATUS selecione uma opção Válida!", "AVISO", JOptionPane.WARNING_MESSAGE);
            } else {
                Chamado chamado = new Chamado();
                if (txtNumeroChamado.getText().equals(chamado.getNumeroChamado())) {
                    JOptionPane.showMessageDialog(null, "Número do chamado já existe");
                } else {
                    chamado.setNumeroChamado(Integer.parseInt(txtNumeroChamado.getText()));
                    chamado.setContrato(Integer.parseInt(txtContrato.getText()));
                    chamado.setNomeCliente(txtNomeCliente.getText());
                    chamado.setEndereco(txtEndereco.getText());
                    chamado.setContato(txtContato.getText());
                    chamado.setTelefone(txtTelefone.getText());
                    chamado.setEmail(txtEmail.getText());
                    chamado.setProblema(txtProblema.getText());
                    chamado.setObservacao(txtObservação.getText());
                    chamado.setStatus((String) (comboStatus.getSelectedItem()));
                    chamado.setData(txtData.getText());
                    chamadoDao.cadastrarChamado(numeroChamado, chamado);
                    limparCampos();
                    atualizarTabela();
                    btFecharChamado.setEnabled(false);
                    btAlterar.setEnabled(false);
                    btExcluir.setEnabled(false);
                    txtContrato.setEnabled(true);
                    jtChamados.setSelectedIndex(1);
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro no cadastro de Chamado", "ERRO", JOptionPane.WARNING_MESSAGE);
            throw new RuntimeException(erro);
        }

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparTelaActionPerformed
        // TODO add your handling code here:
        limparCampos();
        btCadastrar.setEnabled(true);
    }//GEN-LAST:event_btLimparTelaActionPerformed

    private void btCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClienteActionPerformed
        // TODO add your handling code here:
        if (enviarContrato == null) {
            enviarContrato = new TelaClientes();
            enviarContrato.setVisible(true);
            enviarContrato.receberDadosChamadosContrato(txtContrato.getText());
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_btCadastrarClienteActionPerformed

    private void tabelaChamadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaChamadosKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaChamadosKeyPressed

    private void tabelaChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaChamadosMouseClicked
        // TODO add your handling code here:
        jtChamados.setSelectedIndex(0);
        txtNumeroChamado.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_NUMERO_CHAMADO).toString());
        txtContrato.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_CONTRATO).toString());
        txtNomeCliente.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_NOME_CLIENTE).toString());
        txtEndereco.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_ENDERECO).toString());
        txtContato.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_CONTATO).toString());
        txtTelefone.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_TELEFONE).toString());
        txtEmail.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_EMAIL).toString());
        txtProblema.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_PROBLEMA).toString());
        txtObservação.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_OBSERVACAO).toString());
        comboStatus.setSelectedItem(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_STATUS).toString());
        txtData.setText(tabelaChamados.getValueAt(tabelaChamados.getSelectedRow(), TabelaModeloChamado.COLUNA_DATA).toString());
        btAlterar.setEnabled(true);
        btExcluir.setEnabled(true);
        btFecharChamado.setEnabled(true);
        txtContrato.setEnabled(false);
        btCadastrar.setEnabled(false);
    }//GEN-LAST:event_tabelaChamadosMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este chamado?", "Exclusão de chamado", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            int numeroChamado = Integer.parseInt(txtNumeroChamado.getText());
            chamadoDao.excluirChamado(numeroChamado);
        }
        limparCampos();
        atualizarTabela();
        btExcluir.setEnabled(false);
        btAlterar.setEnabled(false);
        btFecharChamado.setEnabled(false);
        btCadastrar.setEnabled(true);
        jtChamados.setSelectedIndex(1);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:

        if (txtNumeroChamado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo NÚMERO DO CHAMADO não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
        } else if (txtContrato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo CONTRATO não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
        } else if (txtProblema.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo PROBLEMA não pode estar em branco!", "AVISO", JOptionPane.WARNING_MESSAGE);
        } else if (comboStatus.getSelectedItem().equals("Selecione uma opção")) {
            JOptionPane.showMessageDialog(null, "Em STATUS selecione uma opção Válida!", "AVISO", JOptionPane.WARNING_MESSAGE);
        } else {
            Chamado chamado = new Chamado();
            chamado.setNumeroChamado(Integer.parseInt(txtNumeroChamado.getText()));
            chamado.setContrato(Integer.parseInt(txtContrato.getText()));
            chamado.setNomeCliente(txtNomeCliente.getText());
            chamado.setEndereco(txtEndereco.getText());
            chamado.setContato(txtContato.getText());
            chamado.setTelefone(txtTelefone.getText());
            chamado.setEmail(txtEmail.getText());
            chamado.setProblema(txtProblema.getText());
            chamado.setObservacao(txtObservação.getText());
            chamado.setStatus((String) (comboStatus.getSelectedItem()));
            chamado.setData(txtData.getText());
            chamadoDao.alterarChamado(chamado);
            limparCampos();
            atualizarTabela();
            btFecharChamado.setEnabled(false);
            btAlterar.setEnabled(false);
            btExcluir.setEnabled(false);
            txtContrato.setEnabled(true);
            btCadastrar.setEnabled(true);
            jtChamados.setSelectedIndex(1);
            jtChamados.setSelectedIndex(1);
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void txtConsultaNumeroChamadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConsultaNumeroChamadoKeyPressed
        // TODO add your handling code here:
        String numeroChamado = txtConsultaNumeroChamado.getText();
        tabelaChamados.setModel(new TabelaModeloChamado(new ChamadoDao().listarChamadoTabelaPorNumeroChamado(numeroChamado)));
    }//GEN-LAST:event_txtConsultaNumeroChamadoKeyPressed

    private void btFecharChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharChamadoActionPerformed
        // TODO add your handling code here:
        if (enviar == null) {
            enviar = new TelaFecharChamado();
            enviar.setVisible(true);
            enviar.receberDadosChamados(txtNumeroChamado.getText(), txtContrato.getText(), txtNomeCliente.getText());
            this.dispose();
        }
    }//GEN-LAST:event_btFecharChamadoActionPerformed

   
    
    private void btDataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataAtualActionPerformed
        // data hora atual
        LocalDateTime agora = LocalDateTime.now();
        //formatar a data
        DateTimeFormatter formatterData = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        //setar a data formatada
        txtData.setText(formatterData.format(agora));
    }//GEN-LAST:event_btDataAtualActionPerformed

    private void txtConsultaNumeroChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaNumeroChamadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaNumeroChamadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaChamados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaChamados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaChamados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChamados.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChamados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscarContrato;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCadastrarCliente;
    private javax.swing.JButton btDataAtual;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFecharChamado;
    private javax.swing.JButton btLimparTela;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jtChamados;
    private javax.swing.JTable tabelaChamados;
    private javax.swing.JTextField txtConsultaNumeroChamado;
    private javax.swing.JTextField txtContato;
    public javax.swing.JTextField txtContrato;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    public javax.swing.JTextField txtNomeCliente;
    public javax.swing.JTextField txtNumeroChamado;
    private javax.swing.JTextField txtObservação;
    private javax.swing.JTextPane txtProblema;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        txtNumeroChamado.setText("");
        txtContrato.setText("");
        txtNomeCliente.setText("");
        txtEndereco.setText("");
        txtContato.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
        txtProblema.setText("");
        txtObservação.setText("");
        comboStatus.setSelectedItem("Selecione uma opção");
        txtData.setText("");
        btExcluir.setEnabled(false);
        btAlterar.setEnabled(false);
        btFecharChamado.setEnabled(false);
        txtContrato.setEnabled(true);
    }

    public void receberDadosCliente(String text1, String text2, String text3, String text4, String text5, String text6) {
        txtContrato.setText(text1);
        txtNomeCliente.setText(text2);
        txtEndereco.setText(text3);
        txtContato.setText(text4);
        txtTelefone.setText(text5);
        txtEmail.setText(text6);
    }
}
