/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cc.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author alafaria
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(getToolkit().createImage(getClass().getResource("/imagens/simpress_logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/papel_parede.png"));
        Image image = icon.getImage();
        jLayeredPane1 = new javax.swing.JLayeredPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuNovoCliente = new javax.swing.JMenuItem();
        menuConsultarCliente = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuNovoChamado = new javax.swing.JMenuItem();
        menuConsultarChamado = new javax.swing.JMenuItem();
        menuFecharChamado = new javax.swing.JMenuItem();
        menuConsultarChamadosFechados = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuNovoUsuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Chamados");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Clientes");

        menuNovoCliente.setText("Novo Cliente");
        menuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuNovoCliente);

        menuConsultarCliente.setText("Consultar Cliente");
        menuConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuConsultarCliente);

        jMenuBar1.add(jMenu3);

        menuRelatorios.setText("Chamados");

        menuNovoChamado.setText("Novo Chamado");
        menuNovoChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoChamadoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuNovoChamado);

        menuConsultarChamado.setText("Consultar Chamado");
        menuConsultarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarChamadoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuConsultarChamado);

        menuFecharChamado.setText("Fechar Chamado");
        menuFecharChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFecharChamadoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuFecharChamado);

        menuConsultarChamadosFechados.setText("Consultar Chamados Fechados");
        menuConsultarChamadosFechados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarChamadosFechadosActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuConsultarChamadosFechados);

        menuConsultar.setText("Relatórios");
        menuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuConsultar);

        jMenuBar1.add(menuRelatorios);

        jMenu4.setText("Usuários");

        menuNovoUsuario.setText("Novo Usuário");
        menuNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(menuNovoUsuario);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        menuSobre.setText("Sobre");
        jMenu5.add(menuSobre);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoUsuarioActionPerformed
        // TODO add your handling code here:
        TelaUsuarios telaUsuarios = new TelaUsuarios();
        telaUsuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNovoUsuarioActionPerformed

    private void menuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoClienteActionPerformed
        // TODO add your handling code here:
        TelaClientes telaClientes = new TelaClientes();
        telaClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNovoClienteActionPerformed

    private void menuConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarClienteActionPerformed
        // TODO add your handling code here:
        TelaClientes telaClientes = new TelaClientes();
        telaClientes.jtCadastroCliente.setSelectedIndex(1);
        telaClientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuConsultarClienteActionPerformed

    private void menuNovoChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoChamadoActionPerformed
        // TODO add your handling code here:
        TelaChamados telaCadastroChamados = new TelaChamados();
        telaCadastroChamados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuNovoChamadoActionPerformed

    private void menuConsultarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarChamadoActionPerformed
        // TODO add your handling code here:
        TelaChamados telaChamados = new TelaChamados();
        telaChamados.jtChamados.setSelectedIndex(1);
        telaChamados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuConsultarChamadoActionPerformed

    private void menuFecharChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFecharChamadoActionPerformed
        // TODO add your handling code here:
        TelaFecharChamado telaFecharChamado = new TelaFecharChamado();
        telaFecharChamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuFecharChamadoActionPerformed

    private void menuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarActionPerformed
        // TODO add your handling code here:
        TelaRelatoriosChamados telaRelatorioChamados = new TelaRelatoriosChamados();
        telaRelatorioChamados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuConsultarActionPerformed

    private void menuConsultarChamadosFechadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarChamadosFechadosActionPerformed
        // TODO add your handling code here:
        TelaFecharChamado telaFecharChamado = new TelaFecharChamado();
        telaFecharChamado.jtChamadosFechados.setSelectedIndex(1);
        telaFecharChamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuConsultarChamadosFechadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuConsultar;
    private javax.swing.JMenuItem menuConsultarChamado;
    private javax.swing.JMenuItem menuConsultarChamadosFechados;
    private javax.swing.JMenuItem menuConsultarCliente;
    private javax.swing.JMenuItem menuFecharChamado;
    private javax.swing.JMenuItem menuNovoChamado;
    private javax.swing.JMenuItem menuNovoCliente;
    private javax.swing.JMenuItem menuNovoUsuario;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
}
